---
name: Text-Chord-Piano
version: 0.0.1
author:
  - 'Dai Okabayashi <genkivogue@ybb.ne.jp>'
abstract: This module is a chord table generator of Piano by the text
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Test::More: 0
  version: 0
provides:
  Text::Chord::Piano:
    file: lib/Text/Chord/Piano.pm
    version: 0.0.1
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
